### ISSUE TITLE
Missing midi.h

### ISSUE THREAD

**Issue by kkostenkov** [yashas-hm/Arduino-MIDI-Drums#1]
Fresh install of Arduino IDE does not have a midi.h file and end up with compile error.
Please update repo or add a page to the docs that one will need to [download a lib](https://github.com/FortySevenEffects/arduino_midi_library#getting-started)

**Comment by kkostenkov** [comment]
Also, as I found out, it seems like you miss [LoopMidi](http://www.tobias-erichsen.de/software/loopmidi.html) installation. But that is a mandatory part of putting it all together,

**Comment by yashas-hm** [comment]
Added to the readme thanks 👍🏻
